language: objective-c
cache: cocoapods
podfile: Example/Podfile
osx_image: xcode7.2
xcode_sdk: iphonesimulator
env:
  global:
    - BUILD_LOG=build.log
    - XCODE_WORKSPACE=Example/log4cxx.xcworkspace
    - XCODE_SCHEME=log4cxx-Example
  matrix:
    - TRAVIS_XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 6s'
    - TRAVIS_XCODE_DESTINATION='platform=iOS Simulator,name=iPhone 5'
before_install:
  - brew update
  - brew outdated xctool || brew upgrade xctool
  - rvm install ruby-2.2.0
  - gem install cocoapods --no-document
  - gem install xcpretty --no-document
  - gem install xcpretty-travis-formatter --no-document
script:
  - set -o pipefail
  - xcodebuild clean test -sdk iphonesimulator -workspace $XCODE_WORKSPACE -scheme $XCODE_SCHEME -destination "$TRAVIS_XCODE_DESTINATION" | xcpretty -f `xcpretty-travis-formatter`